# Generated by Django 4.1.7 on 2023-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.TextField()),
                ('country', models.TextField()),
                ('isocode', models.TextField()),
                ('year', models.TextField()),
                ('total', models.TextField()),
                ('coal', models.TextField()),
                ('oil', models.TextField()),
                ('gas', models.TextField()),
                ('cement', models.TextField()),
                ('flaring', models.TextField()),
                ('other', models.TextField()),
            ],
        ),
    ]
