# Generated by Django 4.1.2 on 2023-03-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emissionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='countrydata',
            fields=[
                ('serialNo', models.TextField(primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('isocode', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='value',
            fields=[
                ('serialNo', models.TextField(primary_key=True, serialize=False)),
                ('coal', models.TextField()),
                ('oil', models.TextField()),
                ('gas', models.TextField()),
                ('cement', models.TextField()),
                ('flaring', models.TextField()),
                ('other', models.TextField()),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='emissionapp.countrydata')),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
